openapi: 3.0.0
info:
    title: SaRA - an SRA SCALR SOC Agent
    description: SOC agent for accessing SRA SCALR XDR Resources, vulnerability management, asset data, siem, data lake, purple teams, pen tests
    version: "0.1"
paths:
    /chat:
      post:
        summary: Interact with SaRA Agent for XDR Resources, vulnerability management, asset data, siem, data lake, purple teams, pen tests
        description: Used for all interactions with SaRA agent
        requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: string containing prompt from agent
        responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Detailed Answer to question
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error