openapi: 3.0.0
info:
    title: Wingman
    description: An API broker for using CrowdStrike via Security Copilot.
    version: 1.0.0
paths:
    /Instructions:
      get:
        summary: Instructions
        description: Use this to get examples on how to use Wingman
        responses:
          '200':
            description: Successful response
            content:
              text/plain:
                schema:
                    type: string
                    example: "Hello Wingman"
    /IncidentList:
      post:
        summary: Retrieve Incident List
        description: Retrieves a list of incidents based on a specified history period.
        requestBody:
          required: false
          content:
            application/json:
              schema:
                type: object
                properties:  
                  history:
                    type: integer
                    description: Number of days to look back for incidents.
                    example: 90
                  hostname:
                    type: string
                    description: A single hostname
                    example: "Crowdstronk"
                  status:
                    type: integer
                    description: The incident status as a number. 20 indicates New status, 25 indicates Reopened Status, 30 indicates in progress status, and 40 indicates closed status
                    enum:
                      - 20  # New
                      - 25  # Reopened
                      - 30  # In Progress
                      - 40  # Closed
                    example: 20
                  description:
                    type: string
                    description: A search string to look for in incident descriptions
                    example: "Privilege Escalation"
                  user:
                    type: string
                    description: a search string based on the username associated with an incident
                    example: "nbluth"
        responses:
          '200':
            description: List of incidents retrieved successfully.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Incident details.
          '403':
            description: Unauthorized access.
    /IncidentDetails:
      post:
        summary: Retrieve Incident Details
        description: Retrieves details of specific incidents based on their IDs.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  ids:
                    type: string
                    description: comma separated list of incident ids
                    example: "incident_id_123, incident_id_234"
        responses:
          '200':
            description: Incident details retrieved successfully.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Incident details.
          '403':
            description: Unauthorized access.
    /TrustScore:
      post:
        summary: Get Trust Score Information for host(s)
        description: Retrieves trust score information for individual assets
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  hostname:
                    type: string
                    description: list of one or more hostnames for a machine
                    example: "bbluth1, nbluth1"
        responses:
          '200':
            description: Host Information
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Detailed information based on security posture of given hosts
          '403':
            description: Unauthorized access.
    /SearchHosts:
      post:
        summary: Search for a list of hosts by hostname 
        description: Retrieves host information and metadata based on a whole or partial hostname supplied.  You must supply the beginning of the hostname and will match rightward. 
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  hostname:
                    type: string
                    description: Search term of the full hostname or a fragment starting at the beginning of the hostname.  performs a right match on the hostname so you can supply one or more characters to search for
                    example: "bbluth"
        responses:
          '200':
            description: Host Information
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Host details including its hardware, names, crowdstrike policies applied, status, bios, agents, and more
          '403':
            description: Unauthorized access.
    /HostInformation:
      post:
        summary: Get all known asset information about a specific hostname
        description: Retrieves all known information about a given host including its hardware, names, crowdstrike policies applied, status, bios, agents, and more
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  hostname:
                    type: string
                    description: list of one or more hostnames for a machine
                    example: "bbluth1, nbluth1"
        responses:
          '200':
            description: Host Information
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Host details including its hardware, names, crowdstrike policies applied, status, bios, agents, and more
          '403':
            description: Unauthorized access.
    /HostPolicyChange:
      post:
        summary: Change what hardening policies apply to a given host in crowdstrike
        description: This endpoint allows you to change the security policy group assigned to a host to increase or decrease security.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  hostname:
                    type: string
                    description: the hostname of the machine
                    example: "GobsDevBox"
        responses:
          '200':
            description: Successfully changed host group
          '403':
            description: Failed to change host group.
    /OnDemandScan:
      post:
        summary: Create, cancel, report on, or check the status of a CrowdStrike On Demand Scan.
        description: If you need to run an on demand scan of a host, you need to give a hostname, and a scan will be created. If you need to cancel a scan, then you need to give the hostname and a scan_id to cancel a specific scan, otherwise if you provide just the hostname it will cancel all current scans associated with the host. Asking for a status and providing the hostname will give you the status of all scans for that host. If you need to know what malicious files were found on a host, you can ask for a on demand scan report and provide the hostname to get all files founds from all scans.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  hostname:
                    type: string
                    description: list of one hostname for a machine
                    example: "bbluth1"
                  action:
                    type: string
                    description: must be one of the following in lowercase - report, create, status, cancel
                    example: "bbluth1"
        responses:
          '200':
            description: On Deman Scan Response
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: The response for the creation of a scan will give you the id, a scan_id and it's current state. The response for a status of an on demand scan will return every scan recorded for that host along with the number of files scanned, those quarantined, or malicious and the Status of each scan. The results for a cancel scan request will return the number of workstations effected, which will correspond to the number of scans that were cancelled, along with the specific scan_id in resources that was canceled. Lastly, the report response will give you the malicious files from each scan, including the filename, filepath, filehash and if it was quarantined for each file found to be malicious.
          '403':
            description: Unauthorized access.
    /SystemHealthCheck:
      get:
        summary: Retrieve Prevention Policy and Exclusion Information 
        description: Retrieves a list of all prevention policies, as well as a gold template of the best possible policy. Each policy is scored for effectiveness. Exclusion information is also pulled with Folder exclusions being more dangerous.
        responses:
          '200':
            description: List of all prevention policies and counts of exclusions.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: prevention policies.
          '403':
            description: Unauthorized access.
    /ActionOnHost:
      post:
        summary: Take an action on a host
        description: Within crowdstrike allows the following actions on a host - 'contain' This action contains the host, which stops any network communications to locations other than the CrowdStrike cloud and IPs specified in your containment policy 'detection_suppress' - Supress detections for the host. detection_unsuppress Allow detections for the host 'lift_containment' - This action lifts containment on the host, which returns its network communications to normal 'hide_host' - This action will delete a host. After the host is deleted, no new detections for that host will be reported via UI or APIs 'unhide_host' - This action will restore a host. Detection reporting will resume after the host is restored
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  hostname:
                    type: string
                    description: list of one or more hostnames for a machine
                    example: "bbluth1, nbluth1"
                  action:
                    type: string
                    description: must be one of the following in lowercase - contain, lift_containment, detection_suppress, detection_unsuppress, hide_host, unhide_host
                    example: "contain"
        responses:
          '200':
            description: Status information
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Status of host
          '403':
            description: Unauthorized access.
    /BlockIoc:
      post:
        summary: Perform a global block for an indicator of compromise
        description: |-
          Create a new IOC by providing a JSON object that includes these key/value pairs:

          **type** (required): The type of the indicator. Valid values:

          - sha256: A hex-encoded sha256 hash string. Length - min: 64, max: 64.

          - md5: A hex-encoded md5 hash string. Length - min 32, max: 32.

          - domain: A domain name. Length - min: 1, max: 200.

          - ipv4: An IPv4 address. Must be a valid IP address.

          - ipv6: An IPv6 address. Must be a valid IP address.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  description:
                    type: string
                    description: description of the indicator being blocked
                    example: "Malicious IP address"
                  comment:
                    type: string
                    description: comment from individual creating the block, such as why its being created.
                    example: "this ioc was observed brute forcing logins"
                  value:
                    type: string
                    description: value of the IOC indicator of compromise.  It must be a valid ipv4 or ipv4 address, or a sha256 file hash, an md5 file hash, or a domain like example.com
                    example: "199.199.199.199"
                  type:
                    type: string
                    description: what specific type of IOC this is.  It may be 
                    enum:
                      - ipv4  
                      - ipv6  
                      - sha256  
                      - md5  
                      - domain
                    example: "ipv4"
                  severity:
                    type: string
                    description: low, medium, high - if unsure use high or do not use
                    enum:
                      - high  
                      - medium  
                      - low  
                    example: "high"
        responses:
          '200':
            description: IOC Blocking success
          '403':
            description: Unauthorized access.