openapi: 3.0.0
info:
    title: Wingman
    description: An API broker for using CrowdStrike via Security Copilot.
    version: "0.1"
paths:
    /:
      get:
        summary: Home Endpoint
        description: Returns a welcome message.
        responses:
          '200':
            description: Successful response
            content:
              text/plain:
                schema:
                    type: string
                    example: "Hello Wingman"
    /incident_list:
      post:
        summary: Retrieve Incident List
        description: Retrieves a list of incidents based on a specified history period.
        requestBody:
          required: false
          content:
            application/json:
              schema:
                type: object
                properties:  
                  history:
                    type: integer
                    description: Number of days to look back for incidents.
                    example: 90
                  hostname:
                    type: string
                    description: A single hostname
                    example: "Crowdstronk"
                  status:
                    type: integer
                    description: The incident status as a number. 20 indicates New status, 25 indicates Reopened Status, 30 indicates in progress status, and 40 indicates closed status
                    enum:
                      - 20  # New
                      - 25  # Reopened
                      - 30  # In Progress
                      - 40  # Closed
                    example: 20
                  description:
                    type: string
                    description: A search string to look for in incident descriptions
                    example: "Privilege Escalation"
                  user:
                    type: string
                    description: a search string based on the username associated with an incident
                    example: "nbluth"
                required: []
        responses:
          '200':
            description: List of incidents retrieved successfully.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Incident details.
          '403':
            description: Unauthorized access.
    /incident_details:
      post:
        summary: Retrieve Incident Details
        description: Retrieves details of specific incidents based on their IDs.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  ids:
                    type: string
                    description: comma separated list of incident ids
                    example: "incident_id_123, incident_id_234"
        responses:
          '200':
            description: Incident details retrieved successfully.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Incident details.
          '403':
            description: Unauthorized access.
    /trust_score:
      post:
        summary: Get Trust Score Information for host(s)
        description: Retrieves trust score information for individual assets
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  hostname:
                    type: string
                    description: list of one or more hostnames for a machine
                    example: "bbluth1, nbluth1"
        responses:
          '200':
            description: Host Information
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Detailed information based on security posture of given hosts
          '403':
            description: Unauthorized access.
    /search_hosts:
      post:
        summary: Search for a list of hosts by hostname 
        description: Retrieves host information and metadata based on a whole or partial hostname supplied.  You must supply the beginning of the hostname and will match rightward. 
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  hostname:
                    type: string
                    description: Search term of the full hostname or a fragment starting at the beginning of the hostname.  performs a right match on the hostname so you can supply one or more characters to search for
                    example: "bbluth"
        responses:
          '200':
            description: Host Information
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Host details including its hardware, names, crowdstrike policies applied, status, bios, agents, and more
          '403':
            description: Unauthorized access.
    /host_information:
      post:
        summary: Get all known asset information about a specific hostname
        description: Retrieves all known information about a given host including its hardware, names, crowdstrike policies applied, status, bios, agents, and more
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  hostname:
                    type: string
                    description: list of one or more hostnames for a machine
                    example: "bbluth1, nbluth1"
        responses:
          '200':
            description: Host Information
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Host details including its hardware, names, crowdstrike policies applied, status, bios, agents, and more
          '403':
            description: Unauthorized access.
    /system_health_check:
      get:
        summary: Retrieve Prevention Policy and Exclusion Information 
        description: Retrieves a list of all prevention policies, as well as a gold template of the best possible policy. Each policy is scored for effectiveness. Exclusion information is also pulled with Folder exclusions being more dangerous.
        responses:
          '200':
            description: List of all prevention policies and counts of exclusions.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: prevention policies.
          '403':
            description: Unauthorized access.
    /action_on_host:
      post:
        summary: Take an action on a host
        description: Within crowdstrike allows the following actions on a host - 'contain' This action contains the host, which stops any network communications to locations other than the CrowdStrike cloud and IPs specified in your containment policy 'detection_suppress' - Supress detections for the host. detection_unsuppress Allow detections for the host 'lift_containment' - This action lifts containment on the host, which returns its network communications to normal 'hide_host' - This action will delete a host. After the host is deleted, no new detections for that host will be reported via UI or APIs 'unhide_host' - This action will restore a host. Detection reporting will resume after the host is restored
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:  
                  hostname:
                    type: string
                    description: list of one or more hostnames for a machine
                    example: "bbluth1, nbluth1"
                  action:
                    type: string
                    description: must be one of the following in lowercase - contain, lift_containment, detection_suppress, detection_unsuppress, hide_host, unhide_host
                    example: "contain"
        responses:
          '200':
            description: Status information
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: Status of host
          '403':
            description: Unauthorized access.
    /goose_mode:
      get:
        summary: Enables goose mode in Crowdstrike
        description: Goose mode is like turbo-crowdstrike
        responses:
          '200':
            description: Action Completed
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    description: "status message"
          '403':
            description: Unauthorized access.