Descriptor:
  Name: CrowPilot for Crowdstrike
  DisplayName: CrowPilot for Crowdstrike by SRA
  Description: Crowdstrike Falcon plugin for Security Copilot by Security Risk Advisors
  Icon: https://raw.githubusercontent.com/SecurityRiskAdvisors/azure-security-tools/refs/heads/main/wingmanconfig/logo.png
  Settings:
    - Name: InstanceURL
      Label: Instance URL
      Description: The URL of the instance to connect to
      HintText: "e.g. https://example.com"
      SettingType: String
      Required: true
  SupportedAuthTypes:
    - ApiKey
  Authorization:
    Type: APIKey
    Key: x-crowpilot-api-key
    Location: Header
    AuthScheme: ''
SkillGroups:
  - Format: API
    Settings:
      OpenApiSpecURL: https://raw.githubusercontent.com/SecurityRiskAdvisors/azure-security-tools/refs/heads/main/wingmanconfig/openapi.yaml
      EndpointUrlSettingName: InstanceURL
